"""init pipeline schema

Revision ID: 22f7704560fa
Revises: 
Create Date: 2026-03-06 20:13:36.555342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22f7704560fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('CRAWL', 'ANALYSIS', name='jobtype'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('to_state', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_created_at'), 'job_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_events_job_type'), 'job_events', ['job_type'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('prompt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_created_at'), 'prompts', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompts_enabled'), 'prompts', ['enabled'], unique=False)
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_checksum'), 'uploads', ['checksum'], unique=False)
    op.create_index(op.f('ix_uploads_created_at'), 'uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('raw_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('normalized_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'normalized_url', name='uq_companies_upload_normalized_url')
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_upload_id'), 'companies', ['upload_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('general_model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('classify_model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ocr_model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'COMPLETED', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.Column('failed_jobs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.create_index(op.f('ix_runs_prompt_id'), 'runs', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_upload_id'), 'runs', ['upload_id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD', name='crawljobstate'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('last_error_message', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'company_id', name='uq_crawl_jobs_upload_company')
    )
    op.create_index(op.f('ix_crawl_jobs_company_id'), 'crawl_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_created_at'), 'crawl_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_id'), 'crawl_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_state'), 'crawl_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_upload_id'), 'crawl_jobs', ['upload_id'], unique=False)
    op.create_table('crawl_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('crawl_job_id', sa.Uuid(), nullable=False),
    sa.Column('home_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('about_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('product_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('home_status', sa.Integer(), nullable=True),
    sa.Column('about_status', sa.Integer(), nullable=True),
    sa.Column('product_status', sa.Integer(), nullable=True),
    sa.Column('home_markdown_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('about_markdown_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('product_markdown_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('home_screenshot_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('about_screenshot_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('product_screenshot_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('home_ocr_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('about_ocr_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('product_ocr_uri', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_artifacts_company_id'), 'crawl_artifacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_crawl_artifacts_crawl_job_id'), 'crawl_artifacts', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_crawl_artifacts_created_at'), 'crawl_artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawl_artifacts_id'), 'crawl_artifacts', ['id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('crawl_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD', name='analysisjobstate'), nullable=False),
    sa.Column('terminal_state', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('prompt_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('last_error_message', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['crawl_artifact_id'], ['crawl_artifacts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'company_id', name='uq_analysis_jobs_run_company')
    )
    op.create_index(op.f('ix_analysis_jobs_company_id'), 'analysis_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_crawl_artifact_id'), 'analysis_jobs', ['crawl_artifact_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_created_at'), 'analysis_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_run_id'), 'analysis_jobs', ['run_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_state'), 'analysis_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_upload_id'), 'analysis_jobs', ['upload_id'], unique=False)
    op.create_table('classification_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_job_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_label', sa.Enum('POSSIBLE', 'CRAP', 'UNKNOWN', name='predictedlabel'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reasoning_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_job_id', name='uq_classification_results_analysis_job')
    )
    op.create_index(op.f('ix_classification_results_analysis_job_id'), 'classification_results', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_classification_results_created_at'), 'classification_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_classification_results_id'), 'classification_results', ['id'], unique=False)
    op.create_index(op.f('ix_classification_results_predicted_label'), 'classification_results', ['predicted_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classification_results_predicted_label'), table_name='classification_results')
    op.drop_index(op.f('ix_classification_results_id'), table_name='classification_results')
    op.drop_index(op.f('ix_classification_results_created_at'), table_name='classification_results')
    op.drop_index(op.f('ix_classification_results_analysis_job_id'), table_name='classification_results')
    op.drop_table('classification_results')
    op.drop_index(op.f('ix_analysis_jobs_upload_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_state'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_run_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_created_at'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_crawl_artifact_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_company_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_crawl_artifacts_id'), table_name='crawl_artifacts')
    op.drop_index(op.f('ix_crawl_artifacts_created_at'), table_name='crawl_artifacts')
    op.drop_index(op.f('ix_crawl_artifacts_crawl_job_id'), table_name='crawl_artifacts')
    op.drop_index(op.f('ix_crawl_artifacts_company_id'), table_name='crawl_artifacts')
    op.drop_table('crawl_artifacts')
    op.drop_index(op.f('ix_crawl_jobs_upload_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_state'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_created_at'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_company_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_runs_upload_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_prompt_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_companies_upload_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_created_at'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_checksum'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_enabled'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_created_at'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_job_events_job_type'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_created_at'), table_name='job_events')
    op.drop_table('job_events')
    # ### end Alembic commands ###
