"""initial_schema

Revision ID: 62b35fbbba2e
Revises:
Create Date: 2026-05-17 00:39:07.536384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "62b35fbbba2e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaigns_created_at"), "campaigns", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_campaigns_id"), "campaigns", ["id"], unique=False)
    op.create_index(op.f("ix_campaigns_name"), "campaigns", ["name"], unique=False)
    op.create_table(
        "integration_secrets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "field_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("last4", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "field_name", name="uq_integration_secrets_provider_field"
        ),
    )
    op.create_index(
        op.f("ix_integration_secrets_created_at"),
        "integration_secrets",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_secrets_field_name"),
        "integration_secrets",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_secrets_id"), "integration_secrets", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_integration_secrets_provider"),
        "integration_secrets",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_secrets_updated_at"),
        "integration_secrets",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "decision_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("instruction_text", sa.Text(), nullable=True),
        sa.Column(
            "model", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "settings_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_settings_campaign_id"),
        "decision_settings",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_settings_created_at"),
        "decision_settings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_settings_id"), "decision_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_decision_settings_is_active"),
        "decision_settings",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_settings_settings_hash"),
        "decision_settings",
        ["settings_hash"],
        unique=False,
    )
    op.create_table(
        "role_fetch_criteria",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("include_rules_json", sa.JSON(), nullable=True),
        sa.Column("exclude_rules_json", sa.JSON(), nullable=True),
        sa.Column(
            "criteria_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_role_fetch_criteria_campaign_id"),
        "role_fetch_criteria",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_fetch_criteria_created_at"),
        "role_fetch_criteria",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_fetch_criteria_criteria_hash"),
        "role_fetch_criteria",
        ["criteria_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_fetch_criteria_id"), "role_fetch_criteria", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_role_fetch_criteria_is_active"),
        "role_fetch_criteria",
        ["is_active"],
        unique=False,
    )
    op.create_table(
        "scrape_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("instruction_text", sa.Text(), nullable=True),
        sa.Column("structured_rules_json", sa.JSON(), nullable=True),
        sa.Column(
            "settings_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scrape_settings_campaign_id"),
        "scrape_settings",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_settings_created_at"),
        "scrape_settings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_settings_id"), "scrape_settings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scrape_settings_is_active"),
        "scrape_settings",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_settings_settings_hash"),
        "scrape_settings",
        ["settings_hash"],
        unique=False,
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False
        ),
        sa.Column(
            "checksum", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_uploads_campaign_id"), "uploads", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_uploads_checksum"), "uploads", ["checksum"], unique=False)
    op.create_index(
        op.f("ix_uploads_created_at"), "uploads", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_uploads_id"), "uploads", ["id"], unique=False)
    op.create_table(
        "verification_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("selected_count", sa.Integer(), nullable=False),
        sa.Column("queued_count", sa.Integer(), nullable=False),
        sa.Column("verified_count", sa.Integer(), nullable=False),
        sa.Column("valid_count", sa.Integer(), nullable=False),
        sa.Column("invalid_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_batches_campaign_id"),
        "verification_batches",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_batches_created_at"),
        "verification_batches",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_batches_id"), "verification_batches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_verification_batches_state"),
        "verification_batches",
        ["state"],
        unique=False,
    )
    op.create_table(
        "classification_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("decision_settings_id", sa.Uuid(), nullable=True),
        sa.Column("settings_snapshot_json", sa.JSON(), nullable=True),
        sa.Column(
            "settings_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("selected_domain_count", sa.Integer(), nullable=False),
        sa.Column("queued_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_settings_id"],
            ["decision_settings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classification_batches_campaign_id"),
        "classification_batches",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_batches_created_at"),
        "classification_batches",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_batches_decision_settings_id"),
        "classification_batches",
        ["decision_settings_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_batches_id"),
        "classification_batches",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_batches_state"),
        "classification_batches",
        ["state"],
        unique=False,
    )
    op.create_table(
        "email_fetch_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("role_fetch_criteria_id", sa.Uuid(), nullable=True),
        sa.Column("criteria_snapshot_json", sa.JSON(), nullable=True),
        sa.Column(
            "criteria_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("provider_order_json", sa.JSON(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("selected_domain_count", sa.Integer(), nullable=False),
        sa.Column("queued_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_fetch_criteria_id"],
            ["role_fetch_criteria.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_fetch_batches_campaign_id"),
        "email_fetch_batches",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_fetch_batches_created_at"),
        "email_fetch_batches",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_fetch_batches_id"), "email_fetch_batches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_email_fetch_batches_role_fetch_criteria_id"),
        "email_fetch_batches",
        ["role_fetch_criteria_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_fetch_batches_state"),
        "email_fetch_batches",
        ["state"],
        unique=False,
    )
    op.create_table(
        "scrape_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("scrape_settings_id", sa.Uuid(), nullable=True),
        sa.Column("settings_snapshot_json", sa.JSON(), nullable=True),
        sa.Column(
            "settings_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("selected_domain_count", sa.Integer(), nullable=False),
        sa.Column("queued_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scrape_settings_id"],
            ["scrape_settings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scrape_batches_campaign_id"),
        "scrape_batches",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_batches_created_at"),
        "scrape_batches",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_batches_id"), "scrape_batches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scrape_batches_scrape_settings_id"),
        "scrape_batches",
        ["scrape_settings_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_batches_state"), "scrape_batches", ["state"], unique=False
    )
    op.create_table(
        "uploaded_domains",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.Uuid(), nullable=True),
        sa.Column("raw_url", sa.Text(), nullable=False),
        sa.Column(
            "normalized_url",
            sqlmodel.sql.sqltypes.AutoString(length=2048),
            nullable=False,
        ),
        sa.Column(
            "domain", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "dedupe_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "scrape_status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "decision_status",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=True,
        ),
        sa.Column(
            "fetch_status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "verify_status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "campaign_id", "dedupe_key", name="uq_uploaded_domains_campaign_dedupe"
        ),
    )
    op.create_index(
        op.f("ix_uploaded_domains_campaign_id"),
        "uploaded_domains",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_domains_created_at"),
        "uploaded_domains",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_domains_decision_status"),
        "uploaded_domains",
        ["decision_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_domains_dedupe_key"),
        "uploaded_domains",
        ["dedupe_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_domains_domain"), "uploaded_domains", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_uploaded_domains_fetch_status"),
        "uploaded_domains",
        ["fetch_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_domains_id"), "uploaded_domains", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_uploaded_domains_scrape_status"),
        "uploaded_domains",
        ["scrape_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_domains_upload_id"),
        "uploaded_domains",
        ["upload_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uploaded_domains_verify_status"),
        "uploaded_domains",
        ["verify_status"],
        unique=False,
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column("email_fetch_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "criteria_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column(
            "linkedin_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True
        ),
        sa.Column("title_match", sa.Boolean(), nullable=False),
        sa.Column(
            "apollo_person_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "snov_person_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "apollo_email", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.Column(
            "snov_email", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.Column("provider_evidence_json", sa.JSON(), nullable=True),
        sa.Column(
            "selected_email",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=True,
        ),
        sa.Column(
            "selected_email_provider",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=True,
        ),
        sa.Column("verification_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "verified_email_snapshot",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=True,
        ),
        sa.Column(
            "verification_status",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=True,
        ),
        sa.Column(
            "verification_sub_status",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("verification_raw_json", sa.JSON(), nullable=True),
        sa.Column("verification_applied", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["uploaded_domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["email_fetch_batch_id"],
            ["email_fetch_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_batch_id"],
            ["verification_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contacts_apollo_person_id"),
        "contacts",
        ["apollo_person_id"],
        unique=False,
    )
    op.create_index(
        "ix_contacts_campaign_domain",
        "contacts",
        ["campaign_id", "domain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contacts_campaign_id"), "contacts", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_created_at"), "contacts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_criteria_hash"), "contacts", ["criteria_hash"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_domain_id"), "contacts", ["domain_id"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_email_fetch_batch_id"),
        "contacts",
        ["email_fetch_batch_id"],
        unique=False,
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_index(
        op.f("ix_contacts_selected_email"), "contacts", ["selected_email"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_snov_person_id"), "contacts", ["snov_person_id"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_title_match"), "contacts", ["title_match"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_verification_batch_id"),
        "contacts",
        ["verification_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contacts_verification_status"),
        "contacts",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "scrape_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column("scrape_batch_id", sa.Uuid(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("pages_attempted_count", sa.Integer(), nullable=False),
        sa.Column("pages_success_count", sa.Integer(), nullable=False),
        sa.Column("markdown_pages_count", sa.Integer(), nullable=False),
        sa.Column("scraped_pages_json", sa.JSON(), nullable=True),
        sa.Column(
            "error_code", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["uploaded_domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scrape_batch_id"],
            ["scrape_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scrape_results_campaign_id"),
        "scrape_results",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_results_created_at"),
        "scrape_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_results_domain_id"),
        "scrape_results",
        ["domain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_results_id"), "scrape_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scrape_results_scrape_batch_id"),
        "scrape_results",
        ["scrape_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scrape_results_state"), "scrape_results", ["state"], unique=False
    )
    op.create_table(
        "classification_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column("scrape_result_id", sa.Uuid(), nullable=True),
        sa.Column("classification_batch_id", sa.Uuid(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column(
            "predicted_label",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=True,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("reasoning_json", sa.JSON(), nullable=True),
        sa.Column("evidence_json", sa.JSON(), nullable=True),
        sa.Column(
            "input_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "settings_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "manual_label", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "manual_thumbs", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True
        ),
        sa.Column("manual_comment", sa.Text(), nullable=True),
        sa.Column("manually_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["classification_batch_id"],
            ["classification_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["uploaded_domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scrape_result_id"],
            ["scrape_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classification_results_campaign_id"),
        "classification_results",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_classification_batch_id"),
        "classification_results",
        ["classification_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_created_at"),
        "classification_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_domain_id"),
        "classification_results",
        ["domain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_id"),
        "classification_results",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_input_hash"),
        "classification_results",
        ["input_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_predicted_label"),
        "classification_results",
        ["predicted_label"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_scrape_result_id"),
        "classification_results",
        ["scrape_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classification_results_state"),
        "classification_results",
        ["state"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_classification_results_state"), table_name="classification_results"
    )
    op.drop_index(
        op.f("ix_classification_results_scrape_result_id"),
        table_name="classification_results",
    )
    op.drop_index(
        op.f("ix_classification_results_predicted_label"),
        table_name="classification_results",
    )
    op.drop_index(
        op.f("ix_classification_results_input_hash"),
        table_name="classification_results",
    )
    op.drop_index(
        op.f("ix_classification_results_id"), table_name="classification_results"
    )
    op.drop_index(
        op.f("ix_classification_results_domain_id"), table_name="classification_results"
    )
    op.drop_index(
        op.f("ix_classification_results_created_at"),
        table_name="classification_results",
    )
    op.drop_index(
        op.f("ix_classification_results_classification_batch_id"),
        table_name="classification_results",
    )
    op.drop_index(
        op.f("ix_classification_results_campaign_id"),
        table_name="classification_results",
    )
    op.drop_table("classification_results")
    op.drop_index(op.f("ix_scrape_results_state"), table_name="scrape_results")
    op.drop_index(
        op.f("ix_scrape_results_scrape_batch_id"), table_name="scrape_results"
    )
    op.drop_index(op.f("ix_scrape_results_id"), table_name="scrape_results")
    op.drop_index(op.f("ix_scrape_results_domain_id"), table_name="scrape_results")
    op.drop_index(op.f("ix_scrape_results_created_at"), table_name="scrape_results")
    op.drop_index(op.f("ix_scrape_results_campaign_id"), table_name="scrape_results")
    op.drop_table("scrape_results")
    op.drop_index(op.f("ix_contacts_verification_status"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_verification_batch_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_title_match"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_snov_person_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_selected_email"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_email_fetch_batch_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_domain_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_criteria_hash"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_created_at"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_campaign_id"), table_name="contacts")
    op.drop_index("ix_contacts_campaign_domain", table_name="contacts")
    op.drop_index(op.f("ix_contacts_apollo_person_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(
        op.f("ix_uploaded_domains_verify_status"), table_name="uploaded_domains"
    )
    op.drop_index(op.f("ix_uploaded_domains_upload_id"), table_name="uploaded_domains")
    op.drop_index(
        op.f("ix_uploaded_domains_scrape_status"), table_name="uploaded_domains"
    )
    op.drop_index(op.f("ix_uploaded_domains_id"), table_name="uploaded_domains")
    op.drop_index(
        op.f("ix_uploaded_domains_fetch_status"), table_name="uploaded_domains"
    )
    op.drop_index(op.f("ix_uploaded_domains_domain"), table_name="uploaded_domains")
    op.drop_index(op.f("ix_uploaded_domains_dedupe_key"), table_name="uploaded_domains")
    op.drop_index(
        op.f("ix_uploaded_domains_decision_status"), table_name="uploaded_domains"
    )
    op.drop_index(op.f("ix_uploaded_domains_created_at"), table_name="uploaded_domains")
    op.drop_index(
        op.f("ix_uploaded_domains_campaign_id"), table_name="uploaded_domains"
    )
    op.drop_table("uploaded_domains")
    op.drop_index(op.f("ix_scrape_batches_state"), table_name="scrape_batches")
    op.drop_index(
        op.f("ix_scrape_batches_scrape_settings_id"), table_name="scrape_batches"
    )
    op.drop_index(op.f("ix_scrape_batches_id"), table_name="scrape_batches")
    op.drop_index(op.f("ix_scrape_batches_created_at"), table_name="scrape_batches")
    op.drop_index(op.f("ix_scrape_batches_campaign_id"), table_name="scrape_batches")
    op.drop_table("scrape_batches")
    op.drop_index(
        op.f("ix_email_fetch_batches_state"), table_name="email_fetch_batches"
    )
    op.drop_index(
        op.f("ix_email_fetch_batches_role_fetch_criteria_id"),
        table_name="email_fetch_batches",
    )
    op.drop_index(op.f("ix_email_fetch_batches_id"), table_name="email_fetch_batches")
    op.drop_index(
        op.f("ix_email_fetch_batches_created_at"), table_name="email_fetch_batches"
    )
    op.drop_index(
        op.f("ix_email_fetch_batches_campaign_id"), table_name="email_fetch_batches"
    )
    op.drop_table("email_fetch_batches")
    op.drop_index(
        op.f("ix_classification_batches_state"), table_name="classification_batches"
    )
    op.drop_index(
        op.f("ix_classification_batches_id"), table_name="classification_batches"
    )
    op.drop_index(
        op.f("ix_classification_batches_decision_settings_id"),
        table_name="classification_batches",
    )
    op.drop_index(
        op.f("ix_classification_batches_created_at"),
        table_name="classification_batches",
    )
    op.drop_index(
        op.f("ix_classification_batches_campaign_id"),
        table_name="classification_batches",
    )
    op.drop_table("classification_batches")
    op.drop_index(
        op.f("ix_verification_batches_state"), table_name="verification_batches"
    )
    op.drop_index(op.f("ix_verification_batches_id"), table_name="verification_batches")
    op.drop_index(
        op.f("ix_verification_batches_created_at"), table_name="verification_batches"
    )
    op.drop_index(
        op.f("ix_verification_batches_campaign_id"), table_name="verification_batches"
    )
    op.drop_table("verification_batches")
    op.drop_index(op.f("ix_uploads_id"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_created_at"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_checksum"), table_name="uploads")
    op.drop_index(op.f("ix_uploads_campaign_id"), table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(
        op.f("ix_scrape_settings_settings_hash"), table_name="scrape_settings"
    )
    op.drop_index(op.f("ix_scrape_settings_is_active"), table_name="scrape_settings")
    op.drop_index(op.f("ix_scrape_settings_id"), table_name="scrape_settings")
    op.drop_index(op.f("ix_scrape_settings_created_at"), table_name="scrape_settings")
    op.drop_index(op.f("ix_scrape_settings_campaign_id"), table_name="scrape_settings")
    op.drop_table("scrape_settings")
    op.drop_index(
        op.f("ix_role_fetch_criteria_is_active"), table_name="role_fetch_criteria"
    )
    op.drop_index(op.f("ix_role_fetch_criteria_id"), table_name="role_fetch_criteria")
    op.drop_index(
        op.f("ix_role_fetch_criteria_criteria_hash"), table_name="role_fetch_criteria"
    )
    op.drop_index(
        op.f("ix_role_fetch_criteria_created_at"), table_name="role_fetch_criteria"
    )
    op.drop_index(
        op.f("ix_role_fetch_criteria_campaign_id"), table_name="role_fetch_criteria"
    )
    op.drop_table("role_fetch_criteria")
    op.drop_index(
        op.f("ix_decision_settings_settings_hash"), table_name="decision_settings"
    )
    op.drop_index(
        op.f("ix_decision_settings_is_active"), table_name="decision_settings"
    )
    op.drop_index(op.f("ix_decision_settings_id"), table_name="decision_settings")
    op.drop_index(
        op.f("ix_decision_settings_created_at"), table_name="decision_settings"
    )
    op.drop_index(
        op.f("ix_decision_settings_campaign_id"), table_name="decision_settings"
    )
    op.drop_table("decision_settings")
    op.drop_index(
        op.f("ix_integration_secrets_updated_at"), table_name="integration_secrets"
    )
    op.drop_index(
        op.f("ix_integration_secrets_provider"), table_name="integration_secrets"
    )
    op.drop_index(op.f("ix_integration_secrets_id"), table_name="integration_secrets")
    op.drop_index(
        op.f("ix_integration_secrets_field_name"), table_name="integration_secrets"
    )
    op.drop_index(
        op.f("ix_integration_secrets_created_at"), table_name="integration_secrets"
    )
    op.drop_table("integration_secrets")
    op.drop_index(op.f("ix_campaigns_name"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_created_at"), table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
