"""add upload validation errors

Revision ID: 9a83ac364758
Revises: d374de3ae642
Create Date: 2026-03-07 00:18:13.661827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a83ac364758'
down_revision: Union[str, Sequence[str], None] = 'd374de3ae642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('validation_errors_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'validation_errors_json')
    # ### end Alembic commands ###
